general:
  #If true, will print debug stack traces. By default, only unexpected exceptions will be printed. If this is true, all handled exceptions will be printed.
  printStackTraces: true
  #If true, uses recursive searching when players join. This is useful for helping to find more alts of players when they join, but disabling it will save processing time.
  recursivePlayerJoin: false
#MySQL Database settings
database:
  #table prefix
  prefix: MCProfiler_